"""SSA top-1,000 names by sex for 2024, used to filter lemon names.

Generated from the U.S. Social Security Administration annual national data
(yob2024.txt). SSA blocked automated retrieval during development, so the same
file was read from this pinned mirror:
https://github.com/dcadata/name-finder/blob/7991ac3634b18672cc2940526fd8f9363c99462d/data/names/yob2024.txt
"""

SSA_TOP_1000_2024 = frozenset(
    """
aadhya aaliyah aarav aaron abby abdiel abdullah abel abigail abner abraham abram
ace ada adalee adaline adalyn adalynn adam adan addilyn addison adelaide adele
adelina adeline adelyn adelynn aden adhara adler adley adonis adrian adriana adrianna
adriel agustin ahmad ahmed aidan aiden aila ailani ailany aileen ainara ainhoa
ainsley aisha aitana akira alaia alaina alaiya alan alana alani alanna alaya
alayah alayna albert alberto alden aldo aleah alec aleena aleia alejandra alejandro
alena alessandra alessandro alessia alessio alex alexa alexander alexandra alexandria alexia alexis
alfonso alfred alfredo ali alia aliana alianna alice alicia alijah alina alison
alisson alistair alivia aliya aliyah aliza allan allen allie allison allyson alma
alondra alonso alonzo alora alvaro alvin alyssa amaia amalia amanda amani amara
amari amaris amaya amayah amber ambrose ameer amelia amelie amias amina amir
amira amirah amiri amiyah amora amos amoura amy amyra ana anahi anaiah
anais anakin analeia analia anastasia anaya ander anders anderson andi andie andre
andrea andres andrew andy angel angela angelica angelina angelo angie anika aniyah
anna annabelle annalise anne annie annika anthony antonella antonio anya apollo april
arabella araceli archer archie arden arely ares ari aria ariah arian ariana
arianna ariel ariella arielle aries arisbeth ariya ariyah arjun arlet arleth arlette
arlo armando armani aron arthur arturo arya aryan asa asaiah asher ashley
ashlyn ashton aspen aspyn astrid athena atlas atreus atticus aubree aubrey audrey
august augustine augustus aura aurelia aurelio aurora austin autumn ava avani averie
avery avi aviana avianna avyaan axel axton aya ayaan ayah ayan ayden
ayla aylani ayleen aylin ayra azael azai azaiah azalea azari azaria azariah
aziel azrael azriel bailee bailey baker banks barbara barrett baylor bear beatrice
beau beckett beckham belen bella bellamy ben benedict benicio benjamin bennett benny
benson bentley berkley bethany bianca billie birdie bjorn blair blaire blake blakely
blaze bo bode boden bodhi bodie bonnie boone boston bowen bradley brady
braelynn brandon brantley braxton brayan brayden braylen braylon brian briana brianna briar
bridger bridget briella brielle briggs brinley bristol brittany brixton brock brodie brody
brooke brooklyn brooklynn brooks bruce bruno bryan bryce brycen bryer brynlee brynleigh
brynn bryson byron cade caden caiden cain cairo cal caleb cali callahan
callan callen callie calliope callum calum calvin camden cameron camila camilla camille
camilo campbell camryn cannon capri carlo carlos carly carmelo carmen carolina caroline
carson carter case casen casey cash cason casper caspian cassandra cassian cassidy
cassius castiel cataleya catalina catherine cattleya cayden cayson cecelia cecilia cedric celeste
celia celina celine cesar chaim chana chance chandler charlee charleigh charles charley
charli charlie charlotte chase chaya chelsea cheyenne chloe chosen chozen chris christian
christina christopher cielo cillian claire clara clare clark clay clayton clementine cleo
clover clyde cody cohen colby cole coleson colette colin collin collins colsen
colson colt colten colter colton conner connor conor conrad cooper cora coraline
corbin corey creed crew cristian crue cruz curtis cynthia cyrus dafne dahlia
daisy dakari dakota daleyza dalia dallas dalton damari damian damien damir damon
dane dangelo dani daniel daniela daniella danielle danna danny dante daphne darcy
darian dariel dario darius darren darwin dash david davina davis dawson dax
daxton dayana deacon dean deborah declan delaney delilah della demi dennis denver
dereck derek derrick desmond destiny devin devon dexter diana diego dilan dillon
dimitri dior dominic dominick donald donovan dorian dorothy douglas drake dream drew
duke dulce dustin dutton dylan easton eddie eden edgar edison edith eduardo
edward edwin eiden eileen eithan elaina elaine elani eleanor eleanora elena eli
elia eliam elian eliana elianna elias eliel elijah elina elio elisa elisabeth
elise eliseo elisha eliza elizabeth ella elle elliana ellianna ellie elliot elliott
ellis elodie eloise elora elouise elowen elowyn elsa elsie elyse emanuel ember
emberly emberlynn emelia emely emerald emerie emerson emersyn emery emi emilia emiliana
emiliano emilio emily emir emma emmanuel emmeline emmett emmie emmitt emmy emory
enoch enrique ensley enzo ephraim eren eric erick erik erin ermias ernesto
esme esmeralda esteban estella estelle esther estrella ethan etta eugene eva evan
evander evangeline eve evelyn evelynn everest everett everlee everleigh everly evie evren
ezekiel ezequiel ezra ezrah fabian faith fallon fatima faye felicity felipe felix
fernanda fernando finley finn finnegan finnley fiona fisher fletcher flora florence flynn
ford forest forrest frances francesca francis francisco franco frank frankie franklin frederick
freya freyja gabriel gabriela gabriella gabrielle gael gage galilea garrett gatlin gavin
gemma genesis genevieve george georgia georgina gerardo gia gian giana gianna gianni
gideon giovanna giovanni giselle giuliana gloria goldie grace gracelyn gracelynn gracie grady
graham grant grayson gregory greta grey greyson griffin guillermo guinevere gunnar gunner
gustavo gwen gwendolyn hadassah hadlee hadley hailey haisley haley halle hallie halo
hamza hana hank hanna hannah harlan harlee harley harlow harmoni harmony harold
harper harrison harry harvey hassan hattie haven hayden hayes hazel heath heaven
hector heidi helen helena hendrix henley henrik henry hezekiah holden holland holly
honey hope houston hudson hugh hugo hunter huxley ian ibrahim icelynn idris
ignacio iker ila iliana imani imran inaya indie indigo indy ira irene
iris isaac isabel isabela isabella isabelle isael isaiah isaias ishaan isla ismael
israel issac itzel ivan ivanna ivey ivory ivy iyla izabella izael izaiah
izan jace jack jackson jacob jacqueline jade jaden jagger jahmir jaiden jaime
jairo jakai jakari jake jalen jaliyah jamari james jameson jamie jamir jamison
jane janelle janiyah jared jase jasiah jasiel jasmine jason jasper javier jax
jaxon jaxson jaxton jaxxon jay jayce jaycee jayceon jayden jayla jaylani jayleen
jaylen jayson jaziel jazlyn jazmin jazmine jedidiah jefferson jeffrey jemma jenesis jenna
jennifer jensen jeremiah jeremias jeremy jericho jerry jesiah jesse jessica jessie jesus
jett jettson jianna jimena jimmy jiraiya jireh joanna joaquin jocelyn joe joel
joelle joey johan johanna john johnathan johnny jolene jolie jon jonah jonas
jonathan jones jordan jordyn jorge jose joseph josephine joshua josiah josie josue
journee journey journi jovie joy joziah jream jrue juan judah jude judith
judson julia julian juliana julianna julie julien juliet julieta julietta juliette julio
julius june junior juniper justin kabir kace kade kaden kaeli kahlani kai
kaia kaiden kailani kailany kairo kaisen kaiser kaison kaitlyn kaiya kaizen kalani
kaleb kali kaliyah kallie kamari kamden kameron kamila kamiyah kamryn kane kannon
kara kareem karim karina karla karson karsyn karter kase kasen kash kashton
kason kassidy kataleya katalina kate katelyn katherine kathryn katie kaya kayce kayden
kayla kaylani kaylee kayleigh kaysen kayson keanu keaton keegan kehlani keilani keily
keira keith kellan kelly kelsey kenai kendall kendra kendrick kenji kenna kennedi
kennedy kenneth kensley kenzie kenzo kevin keyla keziah khai khalani khaleesi khalid
khalil khaza khloe kiaan kian kiana kiara kiera kieran killian kimber kimberly
king kingsley kingston kinley kinsley kira knox koa kobe koda koen kohen
kolson kolter kolton kora kori krew krue kyaire kyla kylan kyle kylee
kylen kyler kylian kylie kylo kyra kyree kyren kyrie kyro kyson lacey
lachlan laila lainey laith lakelyn lakelynn lana lance landen landon landyn lane
laney langston lara laura laurel lauren lavender lawrence lawson layla laylani layne
layton lea leah leandro leanna ledger lee legacy legend leia leif leighton
leila leilani leilany leland lena lennon lennox lenora leo leon leona leonard
leonardo leonel leonidas leroy leslie lettie levi lewis lexi leyla lia liam
lian liana liberty lila lilah lilia lilian liliana lilianna lilith lillian lilliana
lillie lilly lily lilyana lina lincoln linda lionel lisa liv livia lochlan
logan lola london londyn lorelai lorelei lorenzo loretta lottie louie louis louisa
louise love loyal luca lucas lucca lucia lucian luciana luciano lucien lucille
lucy luella luis luisa luka lukas luke luna luz lyanna lydia lyla
lylah lyra lyric mabel mac maci macie mack mackenzie macy madalyn madden
maddie maddison maddox madeleine madeline madelyn madelynn madilyn madilynn madison mae maelynn
maeve magdalena maggie magnolia magnus maia maisie maisy major makai makari makayla
makenna makenzie malachi malakai malani malaya malaysia malcolm malia malik maliyah malka
mallory manuel mara marcel marceline marcellus marcelo marco marcos marcus maren margaret
margo margot maria mariah mariam mariana marianna marie mariella marigold marilyn marina
mario marisol marjorie mark marlee marleigh marley marlowe marshall martha martin marvin
mary maryam mason massimo mateo matheo mathew mathias matias matilda matteo matthew
matthias maurice mauricio maverick mavis max maximilian maximiliano maximo maximus maxine maxwell
maya mazie mccoy mckenna mckenzie mckinley meadow megan meilani meir melanie melany
melina melissa melody melvin memphis mercy meredith messiah mia micah michael michaela
michelle miguel mikaela mikayla mila milan milana milani milena miles miley miller
millie milo mina mira miracle miranda miriam misael mitchell mohamed mohammad mohammed
moises molly monica monroe mordechai morgan moses moshe muhammad murphy musa mustafa
mya myla mylah myles mylo myra nadia nala nalani nancy naomi nash
nasir natalia natalie nataly natasha nathan nathanael nathaniel navy naya nayeli nazir
nehemiah neil nellie nelson neo neriah nevaeh nia nicholas nico nicolas nicole
niko nikolai nikolas nina nixon noa noah noe noel noelle noemi nola
nolan noor nora norah nova novah novalee nyla nylah nyomi oaklee oakleigh
oakley oaklyn oaklynn ocean octavia odin olive oliver olivia omar omari onyx
opal ophelia orion orlando oscar osiris otis otto owen ozias ozzy pablo
paige paislee paisley palmer paloma paris parker patrick paul paula paulina paxton
payton pearl pedro penelope penny persephone peter peyton philip phillip phoebe phoenix
pierce piper poppy porter presley preston prince princeton priscilla promise quentin quincy
quinn quinton rachel raegan raelyn raelynn rafael raiden raina ramon ramona raphael
raul raven ray raya rayan rayden raylan raymond rayna rayne reagan rebecca
rebekah reece reed reese regina reid reign reina remi remington remy renata
rene reuben rex rey reya reyna rhea rhett rhodes rhys ricardo richard
ricky ridge riggs riley rio river rivka robert roberto robin rocco rocky
rodrigo roger rohan roland roman rome romeo romina romy ronald ronan ronin
ronnie rory rosa rosalee rosalia rosalie rosalina rosalyn rose rosemary rosie rowan
rowdy rowen rowyn roy royal royalty royce ruben ruby rudy russell ruth
ruthie ryan ryatt ryder ryker rylan ryland rylee ryleigh rylie saanvi sabrina
sadie sage saige saint salem salma salome salvador salvatore sam samantha samara
samir samira samson samuel santana santiago santino santos sara sarah sarahi sarai
sariyah sasha saul savannah sawyer saylor scarlet scarlett scott scottie scout sean
sebastian selah selena selene seraphina serena serenity sergio seth seven sevyn shane
shawn shelby shepard shepherd shiloh shimon shlomo shmuel siena sienna sierra silas
simon sincere siya sky skye skyla skylar skyler sloan sloane sofia sol
solana soleil solomon sonny sophia sophie soraya soren spencer stanley stefan stella
stephanie stephen sterling stetson steven stevie stormi sullivan summer sunny sutton sydney
sylas sylvia sylvie tadeo talia tallulah tanner tate tatum taylor taytum teagan
teddy teo teresa tessa thaddeus thalia thea theo theodora theodore thiago thomas
tiana tiffany tilly timothy titus tobias tomas tommy tony trace travis treasure
trenton trevor trey trinity tripp tristan troy tru truce true truett tucker
ty tyler tyson ulises uriah uriel vada valentin valentina valentino valeria valerie
valery van vance vanessa veda vera veronica vicente victor victoria vienna vihaan
vincent vincenzo violet violeta violette virginia vivian viviana vivienne wade walker wallace
walter warren watson waverly waylen waylon wayne wells wes wesley wesson westin
westley weston westyn whitley wilder willa william willow wilson winnie winona winston
winter wren wrenlee wrenleigh wrenley wyatt wylder wynter xander xavier ximena xiomara
xyla yaakov yael yahir yahya yamileth yara yareli yaretzi yasmin yehuda yeshua
yisroel yitzchok yosef yousef yusra yusuf zachariah zachary zahir zahra zaid zaiden
zain zainab zaire zakai zamir zander zane zaniyah zara zaria zariah zariyah
zavier zayd zayden zayla zaylee zaylen zayn zayne zechariah zeke zelda zen
zendaya zev zion zoe zoey zora zoya zuri zyair zyaire zyla zymir
zyon
    """.split()  # noqa: SIM905 - compact generated data
)
